### ISSUE TITLE
Debezium server is failing to create a table because of an invalid table identifier.

### ISSUE THREAD

**Issue by mevadadhruv** [memiiso/debezium-server-iceberg#368] opened 2024-06-24 07:36 UTC
hi @ismailsimsek ,
                           we move further actually from that last error(https://github.com/memiiso/debezium-server-iceberg/issues/341), now we have done all the practice we Chris Cranford (Naros)'s blog and debezium blog has said all the privileges from oracle database but without kafka now we are getting issue like this (please check the attachment) where the error message in the log indicates that the Debezium server is failing to create a table due to an invalid table identifier: apacheiceberg.debeziumcdc_aws_DNT_TEST. This error occurs while processing change data capture (CDC) events using the Iceberg sink connector.
we hope that we'll finds solution for this time.

Thank you,
Dhruv Mevada
![image (1)](https://github.com/memiiso/debezium-server-iceberg/assets/109581220/d74a4ce6-fe18-4289-9e1c-f2292e40ee08)

**Comment by ismailsimsek** [comment] 2024-06-24 08:03
duplicate of #369 

@mevadadhruv please don't open duplicate ttickets

**Closed by ismailsimsek** 2024-06-24 08:03 UTC
